blogger/config/routes.rb
Rails.application.routes.draw do
    root to: 'articles#index'
    resources :articles do
        resources :comments
    end
    resources :tags #initializes the RESTful controller actions for the collection named 
end

blogger/app/models/article.rb
class Article < ActiveRecord::Base
    has_many :comments
    has_many :taggings
    has_many :tags, through: :taggings
    has_attached_file :image #This has_attached_file method is part of the paperclip library. With that declaration, paperclip will understand that this model should accept a file attachment and that there are fields to store information about that file which start with image_ in this model’s database table.
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"] #validation of filetype is REQUIRED
    
    def tag_list
        self.tags.collect do |tag|
            tag.name #creates an array of the article's tags; we want to show the actual text of the tag
        end.join(", ")
    end
    
    def tag_list=(tags_string)
        tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
        new_or_found_tags = tag_names.collect{ |name| Tag.find_or_create_by(name: name) } #find_or_create_by in this instance goes through each element in 'tag_names' and tries to find a match in the Tag collection.  If there's a match, it associates that found tag with the article; if not, it creates a new tag in Tag, and adds an association of the tag with the article. 
        self.tags = new_or_found_tags
    end
    
end

blogger/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

blogger/app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :taggings
    has_many :articles, through: :taggings #expressing many-to-many relationship between articles and tags, using the "intermediary" :taggings model 
end

blogger/app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

blogger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blogger/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    include ArticlesHelper
    
    def index
        @articles = Article.all #use '@' so that both controller and view can access the variable
    end
    
    def show
        @article = Article.find(params[:id])
        @comment = Comment.new
        @comment.article_id = @article_id
    end
    
    def new
        @article = Article.new
    end
    
    def edit
        @article = Article.find(params[:id])
    end
    
    def create
        @article = Article.new(article_params)
        @article.save #will not be in the database unless saved! 
        flash.notice = "Article '#{@article.title}' created!"
        redirect_to article_path(@article)
    end
    
    def update
        @article = Article.find(params[:id])
        @article.update(article_params)
        
        flash.notice = "Article '#{@article.title}' updated!"
        
        redirect_to articles_path
    end
    
    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        flash.notice = "Article '#{@article.title}' deleted!"
        redirect_to articles_path
    end
    
end

blogger/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def create
        @comment = Comment.new(comment_params)
        @comment.article_id = params[:article_id]
        
        @comment.save
        redirect_to article_path(@comment.article)
    end
    
    def comment_params
        params.require(:comment).permit(:author_name, :body)
    end
end

blogger/app/controllers/tags_controller.rb
class TagsController < ApplicationController
    
    def index
        @tag = Tag.all
    end
    
    def show
        @tag = Tag.find(params[:id])
    end
    
    def destroy
        @tag = Tag.find(params[:id])
        @tag.destroy
        flash.notice = "Tag '#{@tag.name}' deleted!"
        redirect_to tags_path #tags plural will take the user to the index
    end  
    
end

blogger/app/helpers/application_helper.rb
module ApplicationHelper
end

blogger/app/helpers/articles_helper.rb
module ArticlesHelper
    
    def article_params
        params.require(:article).permit(:title, :body, :tag_list, :image)
    end
    
end

blogger/app/helpers/comments_helper.rb
module CommentsHelper
end

blogger/app/helpers/tags_helper.rb
module TagsHelper
end

blogger/app/views/articles/_comment.html.erb
<div>
    <h4>Comment by <%= comment.author_name %></h4>
    <p class="comment"><%= comment.body %></p>
    <p>Posted <%= distance_of_time_in_words(
        comment.article.created_at, comment.created_at) %> ago
    </p>
</div>

blogger/app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
<!-- multipart tells the form that it needs to accept multipart data -->
<ul>
    <% @article.errors.full_messages.each do |error| %> 
    <li><%= error %></li>
    <% end %> 
</ul>
<p>
    <%= f.label :title %><br />
    <%= f.text_field :title %> 
</p>
<p>
    <%= f.label :body %><br />
    <%= f.text_area :body %> 
</p>
<p>
    <%= f.label :tag_list %><br/>
    <%= f.text_field :tag_list %>
</p>
<p>
    <% if @article.image.exists? %>
        <%= image_tag @article.image.url %><br />
    <% end %>
    <%= f.label :image, "Attach an Image" %><br />
    <%= f.file_field :image %>
</p>
<p>
    <%= f.submit %>
</p>
<% end %>

blogger/app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render partial: 'form' %>

blogger/app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
    <% @articles.each do |article| %>
    <li>
        <%= link_to article.title, article_path(article) %>
    </li>
    <% end %>
</ul>

<%= link_to "Create a New Article", new_article_path, class: "new_article" %> <!-- can add class and ID css attributes to end -->

blogger/app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render partial: 'form' %>

blogger/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p>
Tags:
    <% @article.tags.each do |tag| %>
        <%= link_to tag.name, tag_path(tag) %>
    <% end %>
</p>

<p> 
    <% if @article.image.exists? %>
        <%= image_tag @article.image.url %><br />
    <% end %>
</p> 
<!-- image_tag is a method that displays an image, taking the image's URI as a parameter -->

<p><%= @article.body %></p>

<h3>Comments (<%= @article.comments.size %>) </h3>
<%= render partial: 'articles/comment', collection: @article.comments %> <!-- show the 'comment' view partial for every element in the collection '@article.comments' -->
<%= render partial: 'comments/form' %>

<%= link_to "<< Back to Articles List", articles_path %>

<%= link_to "Edit", edit_article_path(@article) %>

<%= link_to "Delete", article_path(@article), 
    method: :delete, 
    data: {confirm: "Really delete the article?"} %> 
<!-- method: tells controller that request is for a delete, as opposed to 'get', data launches a JS prompt confirming deletion -->

blogger/app/views/comments/_form.html.erb
<h3>Post a comment</h3>
<p>
<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :author_name, "Your Name" %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body, "Your Comment" %><br/> <!-- add second parameter to replace default column label (name given in model) with custom text -->
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>
</p>

blogger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="flash"><%= flash.notice %></p>    
<%= yield %> 
<!-- where the view data will be injected --> 
</body>
</html>

blogger/app/views/tags/index.html.erb
<h1>All Tags</h1>

<ul id="tags">
    <% @tag.each do |tag| %>
    <li>
        <%= link_to tag.name, tag_path(tag) %>
        <%= link_to "Delete", tag_path(tag), 
    method: :delete, 
    data: {confirm: "Really delete the tag?"} %> 
    </li>
    <% end %>
</ul>

blogger/app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
    <% @tag.articles.each do |article| %> 
    <li><%= link_to article.title, article_path(article) %></li>
    <% end %>
</ul>